// PHONIXIA - Master Game Data & Lore Repository

import { CompanionProfile, RealmInfo, Quest, IEPGoal, RTIStudentTier, GradeLevel, MageRank } from '../types/game';

export const COMPANION_KAM: CompanionProfile = {
  id: 'kam',
  name: 'Kam',
  title: 'Sound Scout & Echo Warden',
  personality: 'Brave, energetic, tactile, inquisitive, and relentless in pursuit of mystery sounds.',
  lore: 'Hailing from the crystalline shores of Sound Shallows, Kam was gifted the Runestone Echo Goggles by the ancient Scribes of Phonixia. Kam perceives speech sounds as radiant visual vibrations in the air. When words crumble or letters disconnect, Kam wields the Echo Staff to isolate acoustic frequencies and forge pure phonemic bridges. Kam loves action, rhythmic clapping, and hands-on syllable breaking.',
  catchphrase: 'Feel the rhythm, isolate the sound—every word is a realm to be found!',
  specialAbility: 'Echo Sight',
  specialAbilityDesc: 'Illuminates the acoustic sound waves and tactile mouth positions of tricky phonemes without spoiling answers.',
  bondLevel: 5,
  bondXp: 1850,
  unlockedOutfits: ['Echo Scout Tunic', 'Sandstone Wanderer', 'Acoustic Knight Armor'],
  currentOutfit: 'Echo Scout Tunic',
  supportDialogue: {
    greeting: "Hey adventurer! Ready to tune our ears to the magic frequencies of Phonixia?",
    practiceEncouragement: "Let's break this down into sound blocks! Feel where your tongue touches your teeth.",
    struggleSupport: "Hold on, let's take a side trail together! Let's do an Echo Practice mini-game to feel the pure sound in our mouth.",
    masteryCelebration: "Incredible spellcraft! You mapped that word straight into your Lexicon Grimoire!",
  },
};

export const COMPANION_CELINE: CompanionProfile = {
  id: 'celine',
  name: 'Celine',
  title: 'Lexicon Scholar & Morpheme Weaver',
  personality: 'Brilliant, observant, thoughtful, encouraging, and deeply knowledgeable in ancient root magic.',
  lore: 'Apprenticed in the grand archives of Lexicon Empire, Celine carries the Starlight Compass and an enchanted woven quill. Celine views stories as living spells and words as interlocking puzzle pieces forged across thousands of years. Whether untangling Latin prefixes in ancient ruins or deciphering irregular Heart Words on twisting trails, Celine helps travelers understand the deep history and structural anatomy of every morpheme.',
  catchphrase: 'Roots are the ancient anchors; add a prefix or suffix, and language sets sail!',
  specialAbility: 'Morpheme Weave',
  specialAbilityDesc: 'Highlights root origins and semantic relationships, offering structural investigation missions.',
  bondLevel: 5,
  bondXp: 1920,
  unlockedOutfits: ['Starlight Scholar Robes', 'Archive Scribe Attire', 'Lumina High Magus Mantle'],
  currentOutfit: 'Starlight Scholar Robes',
  supportDialogue: {
    greeting: "Greetings, fellow scholar! The scrolls of Phonixia hold secrets waiting for our insight.",
    practiceEncouragement: "Notice the morphology here. What is the base root, and how does the affix change its meaning?",
    struggleSupport: "Do not worry—great linguists learn through inquiry! Let us visit the Morphology Altar for an investigation quest.",
    masteryCelebration: "Brilliantly reasoned! The ancient roots respond to your deep understanding!",
  },
};

export const REALMS: Record<string, RealmInfo> = {
  sound_shallows: {
    id: 'sound_shallows',
    name: 'Sound Shallows',
    subtitle: 'The Crystalline Cradle of Phonemes',
    description: 'Vibrant turquoise tidepools and glowing coral archipelagos where ambient sound waves crystallize into pure phoneme shells. Novices begin here, training their ears to isolate phonemes, count syllables, and feel tactile articulation.',
    themeColor: '#06b6d4',
    bgGradient: 'from-cyan-900 via-teal-950 to-slate-950',
    iconName: 'Waves',
    keySkills: ['Phonemic Awareness', 'Pure Phoneme Isolation', 'Rhyming', 'Syllable Counting', 'Initial & Final Sounds'],
    zones: ['Ripple Shoreline', 'Whispering Grotto', 'Consonant Cove', 'Vowel Reef', 'Echo Caverns'],
    loreKeeper: 'Marina the Tide Scribe',
    boss: 'The Glitch Golem of Silence (Must be disarmed with pure phoneme chords)',
    ambientSound: 'ocean_chimes',
  },
  builders_guild: {
    id: 'builders_guild',
    name: 'Builders Guild',
    subtitle: 'The Great Syllable & Blending Foundry',
    description: 'A colossal steampunk fantasy city of bronze gears, glowing furnace forges, and towering stone masonry. Here, Language Mages forge individual phonemes into CVC, CCVC, and multisyllabic words using the Anvil of Blending.',
    themeColor: '#f59e0b',
    bgGradient: 'from-amber-900 via-orange-950 to-slate-950',
    iconName: 'Hammer',
    keySkills: ['Phonics Decoding', 'Orthographic Mapping', 'CVC & CCVC Blending', 'Six Syllable Types', 'Encoding / Spelling'],
    zones: ['Anvil of Blends', 'Syllable Foundry', 'Suffix Smelter', 'Compound Bridge', 'Decodable Workshop'],
    loreKeeper: 'Master Smith Thaddeus',
    boss: 'The Jumbled Word Colossus (Must be assembled syllable by syllable)',
    ambientSound: 'forge_gears',
  },
  tricky_trails: {
    id: 'tricky_trails',
    name: 'Tricky Trails',
    subtitle: 'The Enchanted Labyrinth of Heart Words',
    description: 'A whimsical, bioluminescent forest where words do not follow regular phonics rules. High-frequency irregular words wander like fireflies. Travelers learn to identify the regular phonetic parts and memorize the "heart part" by heart.',
    themeColor: '#ec4899',
    bgGradient: 'from-pink-900 via-purple-950 to-slate-950',
    iconName: 'Compass',
    keySkills: ['Heart Words', 'High-Frequency Irregular Words', 'Orthographic Mapping of Exceptions', 'Sight Word Automaticity'],
    zones: ['Heartwood Thicket', 'Lantern Clearing', 'Irregular Mire', 'Echo Glade', 'Memory Grove'],
    loreKeeper: 'Lady Hazel of the Lantern',
    boss: 'The Mirage Sphinx (Requires discerning phonetic rules from heart exceptions)',
    ambientSound: 'forest_whispers',
  },
  whispering_peaks: {
    id: 'whispering_peaks',
    name: 'Whispering Peaks',
    subtitle: 'The Alpine Heights of Fluency & Expression',
    description: 'High mist-shrouded mountain peaks crowned with ancient scroll towers. Wind chimes resonate with rhythmic phrasing. Mages here learn fluency—reading with accuracy, optimal rate, and theatrical prosody to breathe life into ancient legends.',
    themeColor: '#8b5cf6',
    bgGradient: 'from-indigo-900 via-purple-950 to-slate-950',
    iconName: 'Wind',
    keySkills: ['Reading Fluency', 'Prosody & Expression', 'Punctuation Magic', 'Comprehension & Inference', 'Story Theatre'],
    zones: ['High Pass Scriptorium', 'Zephyr Library', 'Echo Canyon', 'Summit of Voice', 'Scrollwatch Peak'],
    loreKeeper: 'Archivist Zephyr',
    boss: 'The Monotone Specter (Banished only with rich expressive prosody)',
    ambientSound: 'mountain_wind',
  },
  lexicon_empire: {
    id: 'lexicon_empire',
    name: 'Lexicon Empire',
    subtitle: 'The Eternal Citadel of Morphology & Etymology',
    description: 'A magnificent metropolis of marble columns, starlight observatories, and golden library domes. Here, the highest-ranking Language Mages study Greek and Latin roots, academic vocabulary, semantics, rhetoric, and debate.',
    themeColor: '#eab308',
    bgGradient: 'from-yellow-900 via-amber-950 to-slate-950',
    iconName: 'BookOpen',
    keySkills: ['Morphology (Prefixes, Roots, Suffixes)', 'Greek & Latin Etymology', 'Academic Vocabulary', 'Rhetoric & Debate', 'Linguistics'],
    zones: ['Arch of Roots', 'Hall of Affixes', 'Etymology Observatory', 'Council of Rhetoric', 'The Master Sanctum'],
    loreKeeper: 'High Chancellor Aurelius',
    boss: 'The Babel Titan (Defeated by deconstructing words into historical roots)',
    ambientSound: 'celestial_bells',
  },
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_1',
    title: 'The Pure Vowel of the Tidepool',
    realm: 'sound_shallows',
    curriculumCategory: 'Phonemic Awareness',
    description: 'Travel to Ripple Shoreline with your companion. Distinguish the pure short /æ/ vowel sound (as in apple) from distorted letter names to reactivate the Tide Altar.',
    xpReward: 150,
    runesReward: 40,
    completed: true,
    minLevel: 1,
    challengeType: 'phoneme_hunt',
    challengeData: { targetSound: 'a', symbol: '/æ/', distractors: ['b', 't', 'm'] },
  },
  {
    id: 'quest_2',
    title: 'Forge of the Three Runes (C-A-T)',
    realm: 'builders_guild',
    curriculumCategory: 'Phonics & Blending',
    description: 'Step into the Anvil of Blends. Forge the phonemes /k/ + /æ/ + /t/ into a cohesive word spell to activate the Mechanical Guardian.',
    xpReward: 250,
    runesReward: 65,
    completed: false,
    minLevel: 1,
    challengeType: 'blending',
    challengeData: { phonemes: ['k', 'a', 't'], targetWord: 'CAT', meaning: 'Feline companion spell' },
  },
  {
    id: 'quest_3',
    title: 'The Heart of "SAID"',
    realm: 'tricky_trails',
    curriculumCategory: 'Heart Words',
    description: 'In the Heartwood Thicket, locate the word "SAID". Map the regular sounds /s/ and /d/, and identify the "ai" irregular spelling that must be known by heart.',
    xpReward: 300,
    runesReward: 80,
    completed: false,
    minLevel: 2,
    challengeType: 'heart_word',
    challengeData: {
      word: 'said',
      phonemes: ['s', 'ɛ', 'd'],
      regularParts: ['s', 'd'],
      heartPart: 'ai',
      heartSound: '/ɛ/ (short e sound spelled with ai)',
    },
  },
  {
    id: 'quest_4',
    title: 'Decipher the Tele-Graph Ruin',
    realm: 'lexicon_empire',
    curriculumCategory: 'Morphology & Etymology',
    description: 'At the Arch of Roots, combine the Greek root "tele" (distant) with "graph" (write) to unlock the Ancient Transmitter.',
    xpReward: 450,
    runesReward: 120,
    completed: false,
    minLevel: 4,
    challengeType: 'morphology',
    challengeData: {
      root1: { form: 'tele', meaning: 'distant / far off', origin: 'Greek' },
      root2: { form: 'graph', meaning: 'to write / record', origin: 'Greek' },
      combined: 'telegraph',
      synthesis: 'A device that writes or sends messages across a great distance.',
    },
  },
  {
    id: 'quest_5',
    title: 'The Breath of Prosody',
    realm: 'whispering_peaks',
    curriculumCategory: 'Fluency & Expression',
    description: 'Read the ancient stanza at the High Pass Scriptorium, respecting commas as gentle pauses and exclamation marks with heroic energy.',
    xpReward: 350,
    runesReward: 90,
    completed: false,
    minLevel: 3,
    challengeType: 'prosody',
    challengeData: {
      passage: 'Halt, brave traveler! The wind howls, yet our words hold true.',
      tempoBpm: 110,
    },
  },
];

export const CURRICULUM_MATRIX: Record<GradeLevel, { title: string; focus: string; scienceBasis: string; keyStandards: string[] }> = {
  PreK3: {
    title: 'Acoustic Foundations',
    focus: 'Oral language, environmental sound discrimination, nursery rhymes, listening attention.',
    scienceBasis: 'Early auditory cortex mapping and prosodic sensitivity before print awareness.',
    keyStandards: ['Distinguish speech from ambient sounds', 'Clap to vocal cadence', 'Identify rhyming pairs in chant'],
  },
  PreK4: {
    title: 'Phonological Emergence',
    focus: 'Syllable awareness, onset-rime blending, alliteration, print concepts.',
    scienceBasis: 'Building phonological sensitivity from larger linguistic units (words/syllables) down to onsets.',
    keyStandards: ['Count syllables in spoken names', 'Identify words starting with the same sound', 'Track print left-to-right'],
  },
  Kindergarten: {
    title: 'Phoneme-Grapheme Awakening',
    focus: 'Phonemic awareness (isolation, blending, segmenting), letter-sound correspondence, CVC decoding.',
    scienceBasis: 'Explicit systematic phonics; pairing acoustic phonemes with visual graphemes in working memory.',
    keyStandards: ['Isolate initial/medial/final phonemes', 'Blend 3-phoneme spoken words', 'Write uppercase & lowercase graphemes'],
  },
  'Grade 1': {
    title: 'The Decodable Frontier',
    focus: 'Consonant blends, digraphs (sh, ch, th, ck), vowel teams, silent e, high-frequency heart words.',
    scienceBasis: 'Orthographic mapping through sound-spelling bonding; moving from slow decoding to automatic recognition.',
    keyStandards: ['Decode CCVC/CVCC words', 'Identify irregular spellings in heart words', 'Read decodable texts with 95%+ accuracy'],
  },
  'Grade 2': {
    title: 'Multisyllabic Architecture',
    focus: 'Six syllable types, common prefixes/suffixes, reading fluency, reading comprehension.',
    scienceBasis: 'Chunking words into orthographic syllables prevents cognitive overload in longer words.',
    keyStandards: ['Divide two-syllable words', 'Apply un-, re-, -ful, -less', 'Read with appropriate rate and prosodic inflection'],
  },
  'Grade 3': {
    title: 'Morphological Foundations',
    focus: 'Base words, Latin roots, structural analysis, informational text comprehension, inference.',
    scienceBasis: 'Morphological awareness accelerates vocabulary acquisition exponentially (morpho-phonemic English).',
    keyStandards: ['Identify Latin roots (tract, struct, port)', 'Determine word meaning via affixes', 'Cite textual evidence for inferences'],
  },
  'Grade 4': {
    title: 'Greek Roots & Academic Lexicon',
    focus: 'Greek combining forms (tele, photo, phon, bio), academic tier-2 vocabulary, complex syntax.',
    scienceBasis: 'Etymological awareness supports cross-curricular reading in science, math, and social studies.',
    keyStandards: ['Analyze Greek combining forms', 'Interpret figurative language', 'Synthesize multiple text sources'],
  },
  'Grade 5': {
    title: 'Syntactic Mastery & Rhetoric',
    focus: 'Complex sentence structures, transitional morphemes, author’s purpose, argumentative drafting.',
    scienceBasis: 'Syntactic parsing directly mediates reading comprehension in advanced expository passages.',
    keyStandards: ['Deconstruct compound-complex sentences', 'Evaluate author claims and credibility', 'Write evidence-based arguments'],
  },
  'Grade 6': {
    title: 'Etymological Analysis & Inferences',
    focus: 'Cross-linguistic word origins, subtle denotation vs connotation, critical literacy analysis.',
    scienceBasis: 'Deep orthographic knowledge anchors semantic nuances and metacognitive comprehension monitoring.',
    keyStandards: ['Trace Latin & Greek word evolutions', 'Analyze thematic development across chapters', 'Evaluate bias in informational texts'],
  },
  'Grade 7': {
    title: 'Discourse & Rhetorical Strategies',
    focus: 'Rhetorical appeals (ethos, pathos, logos), structural text analysis, public speaking, research synthesis.',
    scienceBasis: 'Neurolinguistic integration of expressive speech and analytical reading frameworks.',
    keyStandards: ['Deconstruct rhetorical arguments', 'Conduct multi-source research investigations', 'Deliver structured oral presentations'],
  },
  'Grade 8': {
    title: 'Advanced Morphology & Literature',
    focus: 'High-level affixation, literary analysis, irony, perspective, formal debate and counterarguments.',
    scienceBasis: 'Synthesizing abstract conceptual frameworks into structured written and oral exposition.',
    keyStandards: ['Analyze conflicting viewpoints', 'Evaluate logical fallacies', 'Draft formal persuasive essays with counterclaims'],
  },
  'Grade 9-12': {
    title: 'Scholarly Language & Mastery',
    focus: 'Linguistics, etymology of legal/scientific terminology, literary criticism, academic research.',
    scienceBasis: 'Mastery of specialized registers, discipline-specific vocabulary, and advanced cognitive flexibility.',
    keyStandards: ['Examine linguistic evolution of modern English', 'Conduct primary source textual criticism', 'Publish formal analytical dissertations'],
  },
  'Adult Literacy': {
    title: 'Empowerment & Orthographic Mastery',
    focus: 'Dignified, evidence-based phonemic & morphological mastery, workplace literacy, digital fluency, family reading.',
    scienceBasis: 'Leverages adult spoken language vocabulary while systematically rebuilding orthographic decoding pathways.',
    keyStandards: ['Master phoneme-grapheme correspondences without infantalizing material', 'Navigate workplace documents and contracts', 'Read fluently with family and community'],
  },
};

export const MOCK_ONLINE_PLAYERS = [
  { name: 'Aria_SoundSeeker', rank: 'Syllable Smith', level: 14, realm: 'sound_shallows', guild: 'Phoneme Paladins', status: 'Forging Blends' },
  { name: 'Kaelen_The_Mage', rank: 'Lexicon Knight', level: 27, realm: 'lexicon_empire', guild: 'Archivists of Old', status: 'Studying Latin Roots' },
  { name: 'Nova_WordWeaver', rank: 'Decodable Ranger', level: 19, realm: 'tricky_trails', guild: 'Heart Word Trackers', status: 'In Heartwood Thicket' },
  { name: 'Master_Orion', rank: 'MASTER OF PHONIXIA', level: 85, realm: 'whispering_peaks', guild: 'Grand Council', status: 'Teaching Prosody' },
  { name: 'Zoe_EchoWanderer', rank: 'Novice Soundseeker', level: 6, realm: 'sound_shallows', guild: 'Novice Academy', status: 'Exploring Reef' },
];

export const MOCK_IEP_GOALS: IEPGoal[] = [
  {
    id: 'iep_1',
    studentName: 'Marcus T. (Grade 2)',
    domain: 'Phonemic Awareness',
    baseline: 'Marcus isolates initial phonemes in CVC words with 62% accuracy.',
    targetGoal: 'Given 10 spoken 4-phoneme words (CCVC/CVCC), Marcus will orally segment and isolate all phonemes with 90% accuracy across 3 consecutive sessions.',
    targetDate: '2026-11-15',
    currentProgressPct: 78,
    status: 'on_track',
    accommodationsApplied: ['Visual mouth-position video guide', 'Tactile vowel highlight color-coding', 'Extended response time (1.5x)'],
    evidenceDataPoints: [
      { date: '2026-09-08', scorePct: 65, assessmentType: 'Pure Phoneme Isolation Probe' },
      { date: '2026-09-18', scorePct: 72, assessmentType: 'Voxel Sound Shrine Challenge' },
      { date: '2026-09-28', scorePct: 78, assessmentType: 'Blending Forge Quest' },
    ],
  },
  {
    id: 'iep_2',
    studentName: 'Marcus T. (Grade 2)',
    domain: 'Decoding',
    baseline: 'Marcus accurately decodes closed syllable words with short vowels at 55% accuracy.',
    targetGoal: 'Marcus will decode words with digraphs (sh, ch, th, ck) and blends with 85% accuracy in decodable connected text.',
    targetDate: '2026-12-10',
    currentProgressPct: 70,
    status: 'on_track',
    accommodationsApplied: ['OpenDyslexic font mode', 'Companion Kam tactile articulation prompts', 'Audio read-aloud overlay'],
    evidenceDataPoints: [
      { date: '2026-09-05', scorePct: 58, assessmentType: 'Builders Guild Syllable Forge' },
      { date: '2026-09-15', scorePct: 64, assessmentType: 'Digraph Cove Probe' },
      { date: '2026-09-26', scorePct: 70, assessmentType: 'Decodable Scroll Assessment' },
    ],
  },
];

export const MOCK_RTI_TIERS: RTIStudentTier[] = [
  {
    id: 'rti_1',
    name: 'Marcus T.',
    grade: 'Grade 2',
    tier: 2,
    focusArea: 'Digraphs & Vowel Blends',
    interventionMinutesWeekly: 90,
    progressMonitoringTrend: 'accelerating',
    lastAssessmentScore: 78,
    recommendedPractice: 'Sound Shallows Digraph Cove review & Kam Echo Sight',
  },
  {
    id: 'rti_2',
    name: 'Elena R.',
    grade: 'Grade 2',
    tier: 3,
    focusArea: 'Phonological Segmentation & CVC Encoding',
    interventionMinutesWeekly: 150,
    progressMonitoringTrend: 'stable',
    lastAssessmentScore: 58,
    recommendedPractice: 'Montessori Movable Alphabet mode + pure unvoiced stop discrimination',
  },
  {
    id: 'rti_3',
    name: 'Jayden S.',
    grade: 'Grade 2',
    tier: 1,
    focusArea: 'General Grade-Level Fluency & Prosody',
    interventionMinutesWeekly: 30,
    progressMonitoringTrend: 'accelerating',
    lastAssessmentScore: 94,
    recommendedPractice: 'Whispering Peaks Scriptorium Prosody Quests',
  },
  {
    id: 'rti_4',
    name: 'Amira K.',
    grade: 'Grade 2',
    tier: 2,
    focusArea: 'Heart Words & Irregular Orthography',
    interventionMinutesWeekly: 75,
    progressMonitoringTrend: 'accelerating',
    lastAssessmentScore: 82,
    recommendedPractice: 'Tricky Trails Heartwood Altar mapping',
  },
];
